{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fuusy",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 64656,
          "sha512": "89d926b5b421a1092ad1cc71ada0147fbffe903754b6a46efa72b043e951aa30e95bed530e0cc4913d725200eec802d125d6753d2e7a01c38628ca3d485e48b4",
          "sha256": "814808fecde9b95217634d814b7c41acb8a741d8a84e94cee8ef089303209c3d",
          "sha1": "accb69478eddf5fe91b867b7795a22b9155d57cd",
          "md5": "316b683903c543f9c76bef914c332069"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.2.1"
          }
        },
        {
          "group": "pink.madis.apk.arsc",
          "module": "android-chunk-utils",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 64656,
          "sha512": "89d926b5b421a1092ad1cc71ada0147fbffe903754b6a46efa72b043e951aa30e95bed530e0cc4913d725200eec802d125d6753d2e7a01c38628ca3d485e48b4",
          "sha256": "814808fecde9b95217634d814b7c41acb8a741d8a84e94cee8ef089303209c3d",
          "sha1": "accb69478eddf5fe91b867b7795a22b9155d57cd",
          "md5": "316b683903c543f9c76bef914c332069"
        }
      ]
    }
  ]
}
